name: "CI: Build and Test"

on:
  pull_request:
    branches: [main]
    paths:
      - "**.cs"
      - "**.cshtml"
      - "**.tsx"
      - "**.js"
      - "**.json"
      - "**.csproj"
      - "**.props"
      - "**.targets"
      - "**.sln"

jobs:
  dotnet-format:
    name: .Net Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: dotnet-format
    defaults:
      run:
        shell: pwsh

    env:
      ASPNETCORE_ENVIRONMENT: CI
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: 1

    steps:
      - uses: actions/checkout@v4
